### ISSUE TITLE
TODOアプリをつくるので機能洗い出し

### ISSUE THREAD

**Issue by funnythingz** [IsabellaAzu/rails_todo#1]
- [x] リストをつくる
- [x] 新規作成機能をつくる
- [x] 入力内容のチェック機能をつくる
- [x] エラーメッセージ表示機能をつくる
- [x] 編集機能をつくる
- [x] 削除機能をつくる
- [x] TODOをつくる
- [x] タスクがdoneしたらリストから消える
- [x] Herokuにpush

**Comment by IsabellaAzu** [comment]
ついにクリア！

**Comment by funnythingz** [comment]
:+1:
