### ISSUE TITLE
Railsプロジェクトをpushする

### ISSUE THREAD

**Issue by funnythingz** [IsabellaAzu/rails_todo#2]

**Comment by IsabellaAzu** [comment]
・一覧、詳細ページを閲覧できるところまでで、一旦push
・push時にコミッターの設定を誤っていたので修正する

**Comment by IsabellaAzu** [comment]
・一覧、詳細ページを閲覧できるところまでで、一旦push
・push時にコミッターの設定を誤っていたので修正する
